
resources:
- ../base

images:
 - name: hubiinetwork/teamcity-agent-node
   newTag: feature_impl-18

patchesJson6902:
- target:
    version: v1
    kind: StatefulSet
    namespace: teamcity
    name: teamcity-agent
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
