
resources:
- ../base

patchesJson6902:
- target:
    version: v1
    kind: StatefulSet
    namespace: teamcity
    name: teamcity-agent
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
